
insts = OrderedDict()
insts["minimal"] = [
    # tr neglog
    ((3, false, MatLogdetCone()),),
    ((3, true, MatLogdetCone()),),
    ((3, false, MatNegLog()),),
    ((3, true, MatNegLog()),),
    ((3, false, MatNegLogDirect()),),
    ((3, true, MatNegLogDirect()),),
    ((3, false, MatNegLogEigOrd()),),
    # neggeom
    ((3, false, MatNegGeom()),),
    ((3, true, MatNegGeom()),),
    ((3, false, MatNegGeomEFExp()),),
    ((3, true, MatNegGeomEFExp()),),
    ((3, false, MatNegGeomEFPow()),),
    ((3, true, MatNegGeomEFPow()),),
    # tr negentropy
    ((3, false, MatNegEntropy()),),
    ((3, false, MatNegEntropyEigOrd()),),
    # tr negsqrt
    ((3, false, MatNegSqrt()),),
    ((3, false, MatNegSqrtEigOrd()),),
    # tr negpower01
    ((3, false, MatNegPower01(0.7)),),
    ((3, false, MatNegPower01(0.7)),),
    # tr power12
    ((3, false, MatPower12(1.3)),),
    ((3, false, MatPower12EigOrd(1.3)),),
    ]
insts["fast"] = [
    ((30, true, MatNegGeom()),),
    ((15, false, MatNegGeomEFExp()),),
    ((15, false, MatNegGeomEFPow()),),
    ((40, false, MatNegSqrtConj()),),
    ((8, false, MatNegSqrtConjEigOrd()),),
    ((20, false, MatNegSqrtConjDirect()),),
    ((50, false, MatLogdetCone()),),
    ((30, false, MatNegLog()),),
    ((20, true, MatNegLog()),),
    ((6, false, MatNegLogEigOrd()),),
    ((15, false, MatNegLogDirect()),),
    ((10, true, MatNegLogDirect()),),
    ((30, false, MatNegEntropy()),),
    ((8, false, MatNegEntropyEigOrd()),),
    ((30, false, MatPower12(1.5)),),
    ((7, false, MatPower12EigOrd(1.5)),),
    ]
insts["various"] = [
    ((100, false, MatNegGeom()),),
    ((60, true, MatNegGeom()),),
    ((50, false, MatNegGeomEFExp()),),
    ((30, true, MatNegGeomEFPow()),),
    ((100, false, MatNegSqrtConj()),),
    ((12, false, MatNegSqrtConjEigOrd()),),
    ((50, false, MatNegSqrtConjDirect()),),
    ((150, false, MatLogdetCone()),),
    ((80, true, MatLogdetCone()),),
    ((100, false, MatNegLog()),),
    ((50, true, MatNegLog()),),
    ((18, false, MatNegLogEigOrd()), nothing, (default_tol_relax = 1000,)),
    ((80, false, MatNegLogDirect()),),
    ((40, true, MatNegLogDirect()),),
    ((75, false, MatNegEntropy()),),
    ((14, false, MatNegEntropyEigOrd()),),
    ((30, false, MatPower12(1.5)),),
    ((6, false, MatPower12EigOrd(1.5)),),
    ]
return (CovarianceEstJuMP, insts)
