
insts = Dict()
insts["minimal"] = [
    ((false, 1, 2, true, true, false),),
    ((false, 1, 2, false, true, false),),
    ((false, 1, 2, false, false, false),),
    ((false, 3, 1, false, false, false),),
    ((true, :abs1d, 1, true, true, false),),
    ((true, :abs1d, 1, false, true, false),),
    ((false, :motzkin, 3, false, true, false),),
    ]
insts["fast"] = [
    ((false, 1, 30, true, true, false),),
    ((false, 1, 30, false, true, false),),
    ((false, 1, 30, false, false, false),),
    ((false, 2, 8, true, true, false),),
    ((false, 3, 6, true, true, false),),
    ((false, 5, 3, true, true, false),),
    ((false, 10, 1, true, true, false),),
    ((false, 10, 1, false, true, false),),
    ((false, 10, 1, false, false, false),),
    ((false, 4, 4, true, true, false),),
    ((false, 4, 4, false, true, false),),
    ((false, 4, 4, false, false, false),),
    ((true, :abs1d, 3, true, true, false),),
    ((true, :absunit1d, 1, true, true, false),),
    ((true, :absunit1d, 3, true, true, false),),
    ((true, :negabsunit1d, 2, true, true, false),),
    ((true, :absball2d, 1, true, true, false),),
    ((true, :absbox2d, 2, true, true, false),),
    ((true, :negabsbox2d, 1, true, true, false),),
    ((true, :denseunit1d, 2, true, true, false),),
    ((true, :negabsunit1d, 2, false, true, false),),
    ((true, :absball2d, 1, false, true, false),),
    ((true, :negabsbox2d, 1, false, true, false),),
    ((true, :denseunit1d, 2, false, true, false),),
    ((false, :butcher, 2, true, true, false),),
    ((false, :caprasse, 4, true, true, false),),
    ((false, :goldsteinprice, 7, true, true, false),),
    ((false, :goldsteinprice_ball, 6, true, true, false),),
    ((false, :goldsteinprice_ellipsoid, 7, true, true, false),),
    ((false, :heart, 2, true, true, false),),
    ((false, :lotkavolterra, 3, true, true, false),),
    ((false, :magnetism7, 2, true, true, false),),
    ((false, :magnetism7_ball, 2, true, true, false),),
    ((false, :motzkin, 3, true, true, false),),
    ((false, :motzkin_ball, 3, true, true, false),),
    ((false, :motzkin_ellipsoid, 3, true, true, false),),
    ((false, :reactiondiffusion, 4, true, true, false),),
    ((false, :robinson, 8, true, true, false),),
    ((false, :robinson_ball, 8, true, true, false),),
    ((false, :rosenbrock, 5, true, true, false),),
    ((false, :rosenbrock_ball, 5, true, true, false),),
    ((false, :schwefel, 2, true, true, false),),
    ((false, :schwefel_ball, 2, true, true, false),),
    ((false, :lotkavolterra, 3, false, true, false),),
    ((false, :motzkin, 3, false, true, false),),
    ((false, :motzkin_ball, 3, false, true, false),),
    ((false, :schwefel, 2, false, true, false),),
    ((false, :lotkavolterra, 3, false, false, false),),
    ((false, :motzkin, 3, false, false, false),),
    ((false, :motzkin_ball, 3, false, false, false),),
    ]
insts["slow"] = [
    ((false, 4, 5, true, true, false),),
    ((false, 4, 5, false, true, false),),
    ((false, 4, 5, false, false, false),),
    ((false, 2, 30, true, true, false),),
    ((false, 2, 30, false, true, false),),
    ((false, 2, 30, false, false, false),),
    ]
insts["linops"] = [
    ((false, 1, 8, true, true, true),),
    ((false, 2, 5, true, true, true),),
    ((false, 3, 3, true, true, true),),
    ((false, 5, 2, true, true, true),),
    ((false, 3, 3, false, true, true),),
    ((false, 3, 3, false, false, true),),
    ((false, :butcher, 2, true, true, true),),
    ((false, :caprasse, 4, true, true, true),),
    ((false, :goldsteinprice, 7, true, true, true),),
    ]
return (PolyMinNative, insts)
